name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        run: echo "Deploying to GitHub Pages"

      - name: Build Site
        run: |
          npm install
          npx gh-pages -d .
