name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust as needed

      - name: Install dependencies
        run: npm install

      - name: Configure Git user
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${INPUT_EMAIL}"  # Set this in repository secrets


      - name: Build and Deploy Site
        run: |
              npx gh-pages -d . 
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

